version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: agenda-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securityPassword
      POSTGRES_DB: agenda
    ports:
      - "5432:5432"
    networks:
      - agenda-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: agenda-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - agenda-network

networks:
  agenda-network:
    driver: bridge
