spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agenda_db
    username: postgres
    password: securityPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


management:
  endpoints:
    web:
      exposure:
        include: "*"

api:
  security:
    token:
      secret: my-very-secret-key-for-agenda-api
